# Screen settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
BACKGROUND_COLOR = (10, 10, 40)
PARTICLE_COLORS = [(255, 255, 0), (255, 165, 0), (255, 69, 0)]

# Game settings
SPACESHIP_SPEED = 5
COLLECTIBLE_SPEED = 2
PARTICLE_LIFETIME = 30
PARTICLE_SIZE_SMALL = 3
PARTICLE_SIZE_LARGE = 8

# Collectible settings
COLLECTIBLE_SIZE_SMALL = 30  # smaller than spaceship (40x40)
COLLECTIBLE_SIZE_LARGE = 50  # larger than spaceship (40x40)
POINTS_SMALL = 5
POINTS_LARGE = 15
# Screen settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
BACKGROUND_COLOR = (10, 10, 40)
PARTICLE_COLORS = [(255, 255, 0), (255, 165, 0), (255, 69, 0)]

# Game settings
SPACESHIP_SPEED = 5
COLLECTIBLE_SPEED = 2
PARTICLE_LIFETIME = 30
PARTICLE_SIZE_SMALL = 3
PARTICLE_SIZE_LARGE = 8

# Size settings
BASE_SIZE = 40  # Base size for reference
SIZE_MULTIPLIER_SMALL = 0.75
SIZE_MULTIPLIER_LARGE = 1.25

# Spaceship settings
SPACESHIP_BASE_SIZE = BASE_SIZE
SPACESHIP_MIN_SIZE = int(SPACESHIP_BASE_SIZE * SIZE_MULTIPLIER_SMALL)
SPACESHIP_MAX_SIZE = int(SPACESHIP_BASE_SIZE * SIZE_MULTIPLIER_LARGE)

# Collectible settings
COLLECTIBLE_BASE_SIZE = BASE_SIZE
COLLECTIBLE_SIZE_SMALL = int(COLLECTIBLE_BASE_SIZE * SIZE_MULTIPLIER_SMALL)  # 30px
COLLECTIBLE_SIZE_LARGE = int(COLLECTIBLE_BASE_SIZE * SIZE_MULTIPLIER_LARGE)  # 50px
POINTS_SMALL = 5
POINTS_LARGE = 15

